### PR TITLE
patch: Translate: Add zh-rTW Translate

### PR DESCRIPTION
**Pull request by bluehomewu**
Hello,
I'm a Taiwanese, who works on Android and Translation projects.

### CODE REVIEW

**Comment by bluehomewu** [comment]
CC: @1nikolas
Please review it. Thanks you so much.

**Comment by 1nikolas** [comment]
Thanks for this!
There is a small problem though. `translatable="false"` strings can't be translated and will result to an error. You'll have to either remove `translatable="false"` from both the translated `strings.xml` and the original `strings.xml` (in the case of `app_name` and `app_name_short`) or don't include it in your translated xml (everything else with `translatable="false"`).
Also while at it you can also translate the docs link (I think this is the one https://developer.android.com/google/play/integrity/verdict?hl=zh-tw#device-integrity-field)

**Comment by bluehomewu** [comment]
> 

Hi, @1nikolas 
Sorry about that, I forgot to check that flag.
Here's commit for fixup.

**Comment by 1nikolas** [comment]
Looks good thanks

**Comment by bluehomewu** [comment]
> Looks good thanks

Nicee! Hope can get new update for this application soon.

**Pull request merged**
